using System;

namespace FrameWork.NetWork.V4;

/// <summary>
/// Dispatches incoming packets to the appropriate handler method on a packet handler.
/// Implementations are generated by the RpcSourceGenerator as a nested Dispatcher class
/// inside each PacketHandler subclass.
/// </summary>
/// <typeparam name="THandler">The packet handler type.</typeparam>
public interface IPacketDispatcher<in THandler> where THandler : PacketHandler
{
    /// <summary>
    /// Dispatches a packet to the appropriate handler method.
    /// </summary>
    /// <param name="handler">The handler instance (resolved from the connection-scoped DI container).</param>
    /// <param name="opcode">The packet opcode.</param>
    /// <param name="payload">The packet payload bytes (opcode already extracted).</param>
    /// <param name="services">The connection-scoped service provider for resolving [FromServices] parameters.</param>
    /// <param name="serializer">The packet serializer for deserializing request DTOs.</param>
    /// <param name="connection">The connection context passed to handlers that accept IConnectionContext.</param>
    void Dispatch(
        THandler handler,
        byte opcode,
        ReadOnlyMemory<byte> payload,
        IServiceProvider services,
        IPacketSerializer serializer,
        IConnectionContext connection);
}
