using Core.GameWorld.Combat;
using Core.GameWorld.Combat.Abilities;
using Core.GameWorld.Combat.Buffs;
using Core.GameWorld.Components;
using Core.GameWorld.Events;
using Core.GameWorld.Stats;

namespace Core.GameWorld.Entities;

/// <summary>
/// Abstract base for all combat-capable entities (players, creatures, pets).
/// Provides guaranteed <see cref="Health"/>, <see cref="Abilities"/>, <see cref="Level"/>,
/// <see cref="Realm"/>, and <see cref="Faction"/> as direct fields — no component lookup needed.
/// <para>
/// Combat systems can accept <c>UnitEntity</c> as a parameter type and be confident
/// that health, level, abilities, and realm are always available.
/// </para>
/// <para>
/// Component callbacks are wired at construction. Each component signals domain-level
/// facts (e.g. "cast completed", "died"); the entity translates them into region-level
/// <see cref="ITickEvent"/> instances via the protected <see cref="WorldEntity.Emit"/> method.
/// </para>
/// </summary>
public abstract class UnitEntity : WorldEntity
{
    /// <summary>
    /// Shared default <see cref="AbilityEffectExecutor"/> used by all entities unless
    /// overridden via <c>entity.Abilities.EffectExecutor = …</c>.
    /// <para>
    /// Wire <see cref="AbilityEffectExecutor.BuffLookup"/> on this instance at startup
    /// to enable buff invocation globally.
    /// </para>
    /// </summary>
    public static AbilityEffectExecutor SharedEffectExecutor { get; set; } = new();

    protected UnitEntity(ushort objectId, EntityType type, string name, uint maxHealth)
        : base(objectId, type, name)
    {
        Health = new HealthComponent(maxHealth);
        Abilities = new AbilityComponent(this) { EffectExecutor = SharedEffectExecutor };
        Stats = new StatContainer();
        Buffs = new BuffContainer(this);
        Stats.OnMaxHealthChanged = newMax => Health.Max = newMax;

        // ── Wire component callbacks → tick events ──────────────────
        Health.OnDied = () => Emit(new EntityDied(this));

        Abilities.OnCastConfirmed = ctx => Emit(new AbilityCastConfirmed(this, ctx));
        Abilities.OnCastCompleted = ctx => Emit(new AbilityCastCompleted(this, ctx));
        Abilities.OnCastFailed = (ctx, reason) => Emit(new AbilityCastFailed(this, ctx, reason));
        Abilities.OnCooldownApplied = (entry, ms) => Emit(new AbilityCooldownApplied(this, entry, ms));
        Abilities.OnDamageDealt = (caster, result) => Emit(new DamageDealt(
            caster, result.Target, result.AbilityEntry, result.CommandIndex,
            result.Damage, result.Mitigation, result.Absorption,
            result.WasCritical, result.WasDefended, result.DefenseType));
    }

    /// <summary>Health pool — always present on units. Never null.</summary>
    public HealthComponent Health { get; }

    /// <summary>Per-entity ability state (active cast, cooldowns, GCD) — always present on units. Never null.</summary>
    public AbilityComponent Abilities { get; }

    /// <summary>Stat modifier container — always present on units. Never null.</summary>
    public StatContainer Stats { get; }

    /// <summary>Buff container — always present on units. Never null.</summary>
    public BuffContainer Buffs { get; }

    /// <summary>Unit level (1–40 for players, variable for creatures).</summary>
    public byte Level { get; set; }

    /// <summary>Faction affiliation (Order / Destruction / Neutral).</summary>
    public byte Realm { get; set; }

    /// <summary>Raw faction value used for aggression rules.</summary>
    public byte Faction { get; set; }

    /// <summary>Current action points. Consumed by ability casts, regenerated by tick systems.</summary>
    public int ActionPoints { get; set; }

    /// <summary>
    /// OID of the entity's current offensive target. Set by the client via
    /// <c>F_PLAYER_INFO</c> (target-update packet). <c>0</c> = no target selected.
    /// <para>
    /// Read advisorily by <see cref="Combat.Abilities.AbilityComponent"/> to resolve
    /// the target at cast initiation. The region thread may also read this during
    /// action execution.
    /// </para>
    /// </summary>
    public ushort? CurrentTargetOid { get; set; }

    /// <summary>
    /// Override to tick unit-specific state (HP regen, combat timers) before
    /// optional component ticks.
    /// </summary>
    public override void Update(long tick)
    {
        Buffs.Update(tick);
        Stats.Flush();
        Abilities.Update(tick);
        // TODO: HP regen, combat timers (System 4 — remaining steps)
        base.Update(tick);
    }
}
